name: Deploy Cloud Function

on:
  push:
    branches: [master]

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 19
      - run: mvn clean install --batch-mode --errors --fail-at-end
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: java-competency-demo-0.0.1-SNAPSHOT.jar
          path: target/
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_APPLICATION_CREDENTIALS }}

      - name: Deploy Cloud Function
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@v1
        with:
          name: 'vehicle'   # Replace with your Google Cloud Function name
          runtime: 'java17'   # Replace with the appropriate runtime
          event_trigger_type: ${{ secrets.EVENT_TRIGGER_TYPE }}
          event_trigger_resource: 'projects/white-dynamo-394708/topics/vehicle'
          entry_point: 'com.knoldus.cloudfunction.PubSubDataHandler'

      # Example of using the output
      - name: Test the deployed function
        run: curl "${{ steps.deploy.outputs.url }}"
